version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    container_name: postgres_service
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  node:
    container_name: node
    build:
      context: .
      dockerfile: 'Dockerfile'
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}